---
title: "Central Park Squirrels | Tidy Tuesday | 2023-05-23"
format: html
editor: visual
---

```{r}
library(tidytuesdayR)
library(stringr)
library(dplyr)
library(showtext)
library(ggplot2)
library(png)
library(grid)
library(patchwork)
library(ggimage)
library(magick)
library(osmdata)
library(ggmap)
```

## Data import

```{r}
#| message: false
#| warning: false
squirrels_data <- tt_load("2023-05-23")$squirrel_data
colnames(squirrels_data) <- colnames(squirrels_data) %>% 
  str_to_lower() %>% 
  str_replace_all(pattern = " ", replacement = "_")
```

## Data viz

### Fonts

```{r}
font_add_google(
  name = "Syne Mono", 
  family = "Syne Mono"
)
showtext_auto()
```

### Plot

#### Map

```{r}
central_park_bb <- getbb("Central Park")

central_park_map <- get_map(central_park_bb, maptype = "roadmap")

central_park_boundary <- c(
  left = min(squirrels_data$x),
  bottom = min(squirrels_data$y),
  right = max(squirrels_data$x),
  top = max(squirrels_data$y)
)

get_stamenmap(
  bbox = c(left = -95.80204, bottom = 29.38048, right = -94.92313, top = 30.14344),
  maptype = "toner-lite") %>% ggmap() 

map_plot <- ggplot(data = squirrels_data) + 
  aes(
    x = x, 
    y = y
  ) +
  geom_point(
    size = 2,
    alpha = 0.2
  ) + 
  theme(
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    panel.grid = element_blank(), 
    axis.title = element_blank(), 
    axis.text = element_blank(), 
    axis.ticks = element_blank()
  )

map_plot
```

#### Squirrels

```{r}
img_squirrel_statue <- image_read(
  path = "img/squirrel_statue_liberty.png"
  )

squirrels_plot <- image_ggplot(image = img_squirrel_statue)  +
  labs(subtitle = "Where are squirrels in\nCentral Park, NYC?") +
  theme(
    plot.subtitle = element_text(
      hjust = 0.5,
      family = "Syne Mono",
      size = 16,
      margin = margin(
        t = 0,
        r = 0,
        b = 0,
        l = 0
      )
    ),
    plot.margin = margin(
      t = 5.5, 
      r = 35,
      b = 5.5, 
      l = 5.5),
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA)
  )

squirrels_plot
```

#### Final

```{r}
final_plot <- map_plot +
  squirrels_plot +
  plot_layout(design = "112") &
  plot_annotation(
    caption = "Data: 2018 Central Park Squirrel Census | Graphic: Margot Brd\nData (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright"
  ) & 
  theme(
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA), 
    plot.caption = element_text(
      hjust = 0,
      family = "Syne Mono", 
      size = 5
      )
  ) 

final_plot

img_vintage <- readPNG("img/vintage_paper.png", native = TRUE)

# grid.draw(gList(
#   rasterGrob(
#     img_vintage,
#     width = unit(1, "npc"),
#     height = unit(1, "npc")
#   ),
#   patchworkGrob(final_plot)
# ))
```
